export {default as Header} from './Header';
export {default as Home} from './Home';
export {default as Spinner} from './Spinner';
export {default as Search} from './Search';
export {default as MoviesList} from './MoviesList';
export {default as LoadMore} from './LoadMore';
export {default as BreadCrumbs} from './BreadCrumbs';
export {default as MovieHome} from './MovieHome';
export {default as MovieSecondary} from './MovieSecondary';